//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuinielazCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuarios
    {
        public int intUsuarioID { get; set; }
        public string vchNombre { get; set; }
        public string vchUsuario { get; set; }
        public string vchPassword { get; set; }
        public string vchEmail { get; set; }
        public bool bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
    }
}
