//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuinielazCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuarios
    {
        public int intUsuarioID { get; set; }
        public string vchNombre { get; set; }
        public string vchUsuario { get; set; }
        public string vchPassword { get; set; }
        public string vchEmail { get; set; }
        public bool bitActivo { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
    }
}
